-- Generated by CPMGARAGESTUDIOS Lua Matrix IDE
-- Created: 2026-01-14T04-19-55
-- © CPMGARAGESTUDIOS - All rights reserved
-- Unauthorized copying or distribution prohibited

-- Lua script editor

function start()
    gg.alert("Hello GG World")
end

start()

-- GG Function Template
function hackCoins() --Function Name
  gg.setRanges(gg.REGION_ANONYMOUS) --Set Memory Range
  gg.searchNumber("123", gg.TYPE_DWORD) --Search Value 
  gg.refineNumber("123") -- Refine Search
  local results = gg.getResults(100) -- Get Results Before Editing
  gg.editAll("999", gg.TYPE_DWORD) -- Edit Results
  gg.toast("Coins hacked!") -- Small Temporary Message
  gg.clearResults() -- Clears Results Preps For Next Function
end -- Closes Function Properly

-- End of script generated by CPMGARAGESTUDIOS IDE