-- Generated by CPMGARAGESTUDIOS Lua Matrix IDE
-- Created: 2026-01-14T04-09-39
-- © CPMGARAGESTUDIOS - All rights reserved
-- Unauthorized copying or distribution prohibited

--[[
📜 SUPER SIMPLE MOD MENU for GAME GUARDIAN
Built by CPMGARAGESTUDIOS 🧠
🛠️ Use this as a template to make your own mods!
✅ Safe for beginners
]]

-- Show a little welcome message at the top
gg.alert("👋 Welcome to the CPMGARAGESTUDIOS GG MENU!\n\nChoose an option to run a mod.")

-- 🧱 LIST OF MOD OPTIONS (you will see these in the popup menu)
local menu = {
  "💰 Mod Option 1 – Basic Number Hack",
  "🔥 Mod Option 2 – Change Float Value",
  "🔒 Mod Option 3 – Example with FLAGS",
  "🧪 Mod Option 4 – Enter Your Own Number",
  "❌ Exit Script"
}

-- 💰 Mod Option 1: Basic number hack (DWORD means normal numbers)
function mod1()
  gg.alert("This will search for the number 999999 and change it to 99999999.")
  gg.clearResults()
  gg.searchNumber("999999", gg.TYPE_DWORD)
  local found = gg.getResults(20)
  gg.editAll("99999999", gg.TYPE_DWORD)
  gg.clearResults()
  gg.toast("✅ Mod Option 1 finished!")
end

-- 🔥 Mod Option 2: Changes floating point numbers (decimal values)
function mod2()
  gg.alert("This will search for the float value 1.0 and change it to 2.5.")
  gg.clearResults()
  gg.searchNumber("1.0", gg.TYPE_FLOAT)
  local found = gg.getResults(20)
  gg.editAll("2.5", gg.TYPE_FLOAT)
  gg.clearResults()
  gg.toast("✅ Mod Option 2 finished!")
end

-- 🔒 Mod Option 3: Uses FLAGS for advanced memory types (for when basic search fails)
function mod3()
  gg.alert("This searches with flags (advanced memory). Searching 123456 and changing it to 654321.")
  gg.clearResults()
  gg.searchNumber("123456", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
  local found = gg.getResults(10)
  gg.editAll("654321", gg.TYPE_DWORD)
  gg.clearResults()
  gg.toast("✅ Mod Option 3 finished!")
end

-- 🧪 Mod Option 4: You type the number you want to search and change
function mod4()
  local input = gg.prompt({"🔢 What number do you want to find?"}, nil, {"number"})
  if input == nil then
    gg.toast("❌ You didn't type anything.")
    return
  end
  gg.clearResults()
  gg.searchNumber(input[1], gg.TYPE_DWORD)
  local found = gg.getResults(10)
  gg.editAll("9999", gg.TYPE_DWORD)
  gg.clearResults()
  gg.toast("✅ Your value was changed to 9999!")
end

-- 🚪 MAIN MENU LOOP – Keeps running until you choose "Exit"
while true do
  local choice = gg.choice(menu, nil, "📌 Select a Mod Option Below")
  if choice == nil then
    gg.toast("🕐 Waiting...")
    gg.sleep(1000)
  elseif menu[choice] == "❌ Exit Script" then
    gg.toast("👋 Goodbye from CPMGARAGESTUDIOS!")
    os.exit()
  elseif choice == 1 then
    mod1()
  elseif choice == 2 then
    mod2()
  elseif choice == 3 then
    mod3()
  elseif choice == 4 then
    mod4()
  end
end

-- End of script generated by CPMGARAGESTUDIOS IDE